/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alf.gerfarma.view;

import br.com.alf.gerfarma.control.GerFarmaController;
import br.com.alf.gerfarma.model.entity.ItemVenda;
import br.com.alf.gerfarma.model.entity.PreVenda;
import br.com.alf.gerfarma.util.JPAUtil;
import br.com.alf.gerfarma.util.Moeda;
import java.awt.AWTEvent;
import java.awt.Toolkit;
import java.awt.event.AWTEventListener;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acrs
 */
public class DlgCaixa extends javax.swing.JDialog {

    /**
     * Creates new form DlgCaixa
     */
    public DlgCaixa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preencheUsuarioAtual();
        configuraFuncoesDeTeclado();
        preencherDataAtual();
        listarItemsVenda();
        carregarListaDeBandeiras();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoPreVenda = new javax.swing.JLabel();
        txtCodigoPreVenda = new javax.swing.JTextField();
        lblFuncionario = new javax.swing.JLabel();
        lblImagemcaixa = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        pnlValorTotal = new javax.swing.JPanel();
        lblValorTotal = new javax.swing.JLabel();
        pnlMedicamento = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicamento = new javax.swing.JTable();
        pnlValorTotal1 = new javax.swing.JPanel();
        lblValorTotal1 = new javax.swing.JLabel();
        lblCodigoPreVenda1 = new javax.swing.JLabel();
        cbxFormaPagamento = new javax.swing.JComboBox();
        txtDinheiro = new javax.swing.JTextField();
        btnNovo = new javax.swing.JButton();
        btnFinaliza = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblDataHora = new javax.swing.JLabel();
        lblDataHoraValor = new javax.swing.JLabel();
        lblCodigoPreVenda2 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        lblCodigoPreVenda3 = new javax.swing.JLabel();
        cbxBandeira = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GerFarma - Caixa");

        lblCodigoPreVenda.setText("Codígo Pre-venda:");

        txtCodigoPreVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoPreVendaActionPerformed(evt);
            }
        });
        txtCodigoPreVenda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCodigoPreVendaKeyPressed(evt);
            }
        });

        lblFuncionario.setText("Funcionario:");

        lblImagemcaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/caixa64x64.png"))); // NOI18N

        txtFuncionario.setEditable(false);

        pnlValorTotal.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor Total"));

        lblValorTotal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblValorTotal.setForeground(new java.awt.Color(49, 106, 197));
        lblValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTotal.setText("R$ 0,00");

        javax.swing.GroupLayout pnlValorTotalLayout = new javax.swing.GroupLayout(pnlValorTotal);
        pnlValorTotal.setLayout(pnlValorTotalLayout);
        pnlValorTotalLayout.setHorizontalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlValorTotalLayout.setVerticalGroup(
            pnlValorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorTotalLayout.createSequentialGroup()
                .addComponent(lblValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMedicamento.setBorder(javax.swing.BorderFactory.createTitledBorder("Medicamentos"));

        tblMedicamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMedicamento);

        javax.swing.GroupLayout pnlMedicamentoLayout = new javax.swing.GroupLayout(pnlMedicamento);
        pnlMedicamento.setLayout(pnlMedicamentoLayout);
        pnlMedicamentoLayout.setHorizontalGroup(
            pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pnlMedicamentoLayout.setVerticalGroup(
            pnlMedicamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMedicamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlValorTotal1.setBorder(javax.swing.BorderFactory.createTitledBorder("Troco"));

        lblValorTotal1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblValorTotal1.setForeground(new java.awt.Color(49, 106, 197));
        lblValorTotal1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblValorTotal1.setText("R$ 0,00");

        javax.swing.GroupLayout pnlValorTotal1Layout = new javax.swing.GroupLayout(pnlValorTotal1);
        pnlValorTotal1.setLayout(pnlValorTotal1Layout);
        pnlValorTotal1Layout.setHorizontalGroup(
            pnlValorTotal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlValorTotal1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValorTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlValorTotal1Layout.setVerticalGroup(
            pnlValorTotal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlValorTotal1Layout.createSequentialGroup()
                .addComponent(lblValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCodigoPreVenda1.setText("Pagamento:");

        cbxFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dinheiro", "Cartão" }));
        cbxFormaPagamento.setEnabled(false);
        cbxFormaPagamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxFormaPagamentoItemStateChanged(evt);
            }
        });

        txtDinheiro.setEditable(false);
        txtDinheiro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDinheiro.setForeground(new java.awt.Color(49, 106, 197));
        txtDinheiro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDinheiro.setText("0");

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/novo_32x32.png"))); // NOI18N
        btnNovo.setText("F2 Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnFinaliza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/aplicar_32x32.png"))); // NOI18N
        btnFinaliza.setText("F3 Finaliza");
        btnFinaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblDataHora.setText("Data:");

        lblDataHoraValor.setText("23/09/2013 - 17:10");

        lblCodigoPreVenda2.setText("Desconto:");

        txtDesconto.setEditable(false);
        txtDesconto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDesconto.setForeground(new java.awt.Color(49, 106, 197));
        txtDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDesconto.setText("0");

        lblCodigoPreVenda3.setText("Bandeira:");

        cbxBandeira.setEnabled(false);
        cbxBandeira.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxBandeiraItemStateChanged(evt);
            }
        });
        cbxBandeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxBandeiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigoPreVenda)
                            .addComponent(lblFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoPreVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtFuncionario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDataHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataHoraValor)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblImagemcaixa))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoPreVenda1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCodigoPreVenda3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCodigoPreVenda2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnlMedicamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlValorTotal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFinaliza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFuncionario)
                            .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataHora)
                            .addComponent(lblDataHoraValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodigoPreVenda)
                            .addComponent(txtCodigoPreVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblImagemcaixa)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlValorTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFinaliza))
                    .addComponent(pnlMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoPreVenda1)
                    .addComponent(cbxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoPreVenda2)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoPreVenda3)
                    .addComponent(cbxBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed

    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnFinalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaActionPerformed

    }//GEN-LAST:event_btnFinalizaActionPerformed

    private void txtCodigoPreVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoPreVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoPreVendaActionPerformed

    private void txtCodigoPreVendaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoPreVendaKeyPressed
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            btnBuscar.doClick();
        }
    }//GEN-LAST:event_txtCodigoPreVendaKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int codigoPreVenda = 0;
        try {
            codigoPreVenda = Integer.parseInt(txtCodigoPreVenda.getText());
            if (codigoPreVenda == 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Código inválido.");
            txtCodigoPreVenda.requestFocus();
            txtCodigoPreVenda.selectAll();
            return;
        }

        entityManager = JPAUtil.getInstance();
        PreVenda preVenda = entityManager.find(PreVenda.class, codigoPreVenda);

        if (preVenda != null) {
            itemsVenda = preVenda.getItemsVenda();

            cbxBandeira.setEnabled(true);
            cbxFormaPagamento.setEnabled(true);
            cbxFormaPagamento.setSelectedIndex(0);
            txtDesconto.setEditable(true);
        } else {
            itemsVenda = new ArrayList<ItemVenda>();

            cbxBandeira.setEnabled(false);
            cbxFormaPagamento.setEnabled(false);
            JOptionPane.showMessageDialog(this, "PreVenda não encontrada.");
            txtCodigoPreVenda.selectAll();
        }
        mostraValorTotal();
        listarItemsVenda();
        cbxFormaPagamento.setSelectedIndex(0);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxFormaPagamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxFormaPagamentoItemStateChanged
        if (cbxFormaPagamento.getSelectedItem().toString().equals("Dinheiro")) {
            txtDinheiro.setText("0");
            txtDinheiro.setEditable(true);
            txtDinheiro.requestFocus();
            txtDinheiro.selectAll();
        } else {
            double valorTotal = 0;
            for (ItemVenda itemVenda : itemsVenda) {
                valorTotal += itemVenda.getQuantidade() * itemVenda.getValorVendido();
            }
            txtDinheiro.setText(String.valueOf(valorTotal));
            txtDinheiro.setEditable(false);
        }
    }//GEN-LAST:event_cbxFormaPagamentoItemStateChanged

    private void cbxBandeiraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxBandeiraItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBandeiraItemStateChanged

    private void cbxBandeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxBandeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxBandeiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DlgCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DlgCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DlgCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DlgCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgCaixa dialog = new DlgCaixa(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnFinaliza;
    private javax.swing.JButton btnNovo;
    private javax.swing.JComboBox cbxBandeira;
    private javax.swing.JComboBox cbxFormaPagamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoPreVenda;
    private javax.swing.JLabel lblCodigoPreVenda1;
    private javax.swing.JLabel lblCodigoPreVenda2;
    private javax.swing.JLabel lblCodigoPreVenda3;
    private javax.swing.JLabel lblDataHora;
    private javax.swing.JLabel lblDataHoraValor;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblImagemcaixa;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JLabel lblValorTotal1;
    private javax.swing.JPanel pnlMedicamento;
    private javax.swing.JPanel pnlValorTotal;
    private javax.swing.JPanel pnlValorTotal1;
    private javax.swing.JTable tblMedicamento;
    private javax.swing.JTextField txtCodigoPreVenda;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtDinheiro;
    private javax.swing.JTextField txtFuncionario;
    // End of variables declaration//GEN-END:variables

    private List<ItemVenda> itemsVenda = new ArrayList<ItemVenda>();
    private EntityManager entityManager;
    private Query query;

    private Date dataAtual;

    private void preencheUsuarioAtual() {
        txtFuncionario.setText(GerFarmaController.getFuncionarioCorrente().getUsuario());
    }

    private void preencherDataAtual() {
        dataAtual = new Date();
        Calendar calendario = Calendar.getInstance();
        calendario.setTime(dataAtual);

        String dia = String.valueOf(calendario.get(Calendar.DAY_OF_MONTH));
        String mes = String.valueOf(calendario.get(Calendar.MONTH));
        String ano = String.valueOf(calendario.get(Calendar.YEAR));

        String hora = String.valueOf(calendario.get(Calendar.HOUR_OF_DAY));
        String minuto = String.valueOf(calendario.get(Calendar.MINUTE));

        String dataAtualStr = dia + "/" + mes + "/" + ano + " - " + hora + ":" + minuto;
        lblDataHoraValor.setText(dataAtualStr);
    }

    private void configuraFuncoesDeTeclado() {
        Toolkit.getDefaultToolkit().addAWTEventListener(
                new AWTEventListener() {
                    @Override
                    public void eventDispatched(final AWTEvent awt_evt) {
                        final KeyEvent evt = (KeyEvent) awt_evt;

                        switch (evt.getKeyCode()) {
                            case KeyEvent.VK_F2: {
                                btnNovo.doClick();
                                break;
                            }
                            case KeyEvent.VK_F3: {
                                btnFinaliza.doClick();
                                break;
                            }
                        }
                    }
                },
                AWTEvent.KEY_EVENT_MASK
        );
    }

    private void listarItemsVenda() {

        String[] columnNames = new String[]{"Produto", "Qtde.", "Valor Unitário", "Valor Total do Produto"};
        String[][] data = null;

        if (itemsVenda.size() > 0) {
            data = new String[itemsVenda.size()][4];

            int row = 0;
            for (ItemVenda itemVenda : itemsVenda) {
                data[row][0] = itemVenda.getMedicamento().getNome();
                data[row][1] = String.valueOf(itemVenda.getQuantidade());
                data[row][2] = String.valueOf(Moeda.mascaraDinheiro(itemVenda.getValorVendido(), Moeda.DINHEIRO_REAL));
                data[row][3] = String.valueOf(Moeda.mascaraDinheiro(itemVenda.getQuantidade() * itemVenda.getValorVendido(), Moeda.DINHEIRO_REAL));
                row++;
            };
        }
        tblMedicamento.setModel(new DefaultTableModel(data, columnNames));
    }

    private void mostraValorTotal() {
        double valorTotal = 0;
        for (ItemVenda itemVenda : itemsVenda) {
            valorTotal += itemVenda.getQuantidade() * itemVenda.getValorVendido();
        }
        lblValorTotal.setText(Moeda.mascaraDinheiro(valorTotal, Moeda.DINHEIRO_REAL));
    }

    private void carregarListaDeBandeiras() {
        //Buscando nome de clientes do banco
        entityManager = Persistence.createEntityManagerFactory("GERFARMAPU").createEntityManager();
        query = entityManager.createQuery("SELECT c.bandeira FROM Cartao c ORDER BY c.bandeira");
        List<String> bandeiras = query.getResultList();

        //Adicionando nomes de clientes
        cbxBandeira.removeAllItems();
        for (String bandeira : bandeiras) {
            cbxBandeira.addItem(bandeira);
        }
    }

}
