/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.alf.gerfarma.view;

/**
 *
 * @author flavio
 */
public class DlgCompras extends javax.swing.JFrame {

        /**
         * Creates new form DlgCompras
         */
        public DlgCompras() {
                initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the form. WARNING: Do NOT
         * modify this code. The content of this method is always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

                entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("gerfarma?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
                medicamentoQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Medicamento m");
                medicamentoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : medicamentoQuery.getResultList();
                lblFornecedor = new javax.swing.JLabel();
                cbxFornecedor = new javax.swing.JComboBox();
                btnFornecedor = new javax.swing.JButton();
                lblMedicamento = new javax.swing.JLabel();
                cbxMedicamento = new javax.swing.JComboBox();
                btnMedicamento = new javax.swing.JButton();
                Mastertable = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                lblLote = new javax.swing.JLabel();
                lblValidade = new javax.swing.JLabel();
                lblQnteCompra = new javax.swing.JLabel();
                lblQnteeEstqMinimo = new javax.swing.JLabel();
                lblQbteEstoqAtual = new javax.swing.JLabel();
                lblData = new javax.swing.JLabel();
                lblPrecoCusto = new javax.swing.JLabel();
                lblPrecoVenda = new javax.swing.JLabel();
                txtLote = new javax.swing.JTextField();
                txtData = new javax.swing.JTextField();
                txtValidade = new javax.swing.JTextField();
                txtPrecoCusto = new javax.swing.JTextField();
                txtPrecoVenda = new javax.swing.JTextField();
                txtQnteEstoqAtual = new javax.swing.JTextField();
                txtQnteCompra = new javax.swing.JTextField();
                txtQnteEstoqMinimo = new javax.swing.JTextField();
                lblimagem = new javax.swing.JLabel();
                pnlCunsulta = new javax.swing.JPanel();
                lblCunsultaMedicamento = new javax.swing.JLabel();
                lblConsultaCodigo = new javax.swing.JLabel();
                txtConsultaMedicamento = new javax.swing.JTextField();
                txtConsultaCodigo = new javax.swing.JTextField();
                btnFinalizar = new javax.swing.JButton();
                BtnCancelar = new javax.swing.JButton();
                btnEditar = new javax.swing.JButton();
                btnSair = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                lblFornecedor.setText("Fornecedor:");

                cbxFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":::Selecionar o Fornecedor:::" }));

                btnFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/adicionar_16x16.png"))); // NOI18N
                btnFornecedor.setText("Adicionar");

                lblMedicamento.setText("Medicamento:");

                cbxMedicamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { ":::selecionar o Medicamento:::" }));

                btnMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/adicionar_16x16.png"))); // NOI18N
                btnMedicamento.setText("Adicionar");

                org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, medicamentoList, jTable1);
                org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
                columnBinding.setColumnName("Nome");
                columnBinding.setColumnClass(String.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fabricante}"));
                columnBinding.setColumnName("Fabricante");
                columnBinding.setColumnClass(String.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${formula}"));
                columnBinding.setColumnName("Formula");
                columnBinding.setColumnClass(String.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoCusto}"));
                columnBinding.setColumnName("Preco Custo");
                columnBinding.setColumnClass(Double.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoVenda}"));
                columnBinding.setColumnName("Preco Venda");
                columnBinding.setColumnClass(Double.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidadeEstoqueMinimo}"));
                columnBinding.setColumnName("Quantidade Estoque Minimo");
                columnBinding.setColumnClass(Integer.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${quantidadeEstoque}"));
                columnBinding.setColumnName("Quantidade Estoque");
                columnBinding.setColumnClass(Integer.class);
                bindingGroup.addBinding(jTableBinding);
                jTableBinding.bind();
                Mastertable.setViewportView(jTable1);

                lblLote.setText("Lote:");

                lblValidade.setText("Validade:");

                lblQnteCompra.setText("Quantidade de Compra:");

                lblQnteeEstqMinimo.setText("Quantidade Estoque Minimo:");

                lblQbteEstoqAtual.setText("Quantidade Estoque Atual:");

                lblData.setText("Data:");

                lblPrecoCusto.setText("Preço de Custo:");

                lblPrecoVenda.setText("Preço de Venda:");

                lblimagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/comprimido92x92.png"))); // NOI18N

                pnlCunsulta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                lblCunsultaMedicamento.setText("Consulta Por Nome de Medicamento:");

                lblConsultaCodigo.setText("Consulta por Codigo de Compras:");

                javax.swing.GroupLayout pnlCunsultaLayout = new javax.swing.GroupLayout(pnlCunsulta);
                pnlCunsulta.setLayout(pnlCunsultaLayout);
                pnlCunsultaLayout.setHorizontalGroup(
                        pnlCunsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCunsultaLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(pnlCunsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCunsultaMedicamento)
                                        .addComponent(lblConsultaCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlCunsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtConsultaCodigo)
                                        .addComponent(txtConsultaMedicamento)))
                );
                pnlCunsultaLayout.setVerticalGroup(
                        pnlCunsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCunsultaLayout.createSequentialGroup()
                                .addGroup(pnlCunsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCunsultaMedicamento)
                                        .addComponent(txtConsultaMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlCunsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblConsultaCodigo)
                                        .addComponent(txtConsultaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 4, Short.MAX_VALUE))
                );

                btnFinalizar.setText("Finalizar Compra");

                BtnCancelar.setText("Cancelar Compra");

                btnEditar.setText("Editar Compra");

                btnSair.setText("Sair");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(lblMedicamento)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(cbxMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(btnMedicamento)
                                                                        .addGap(254, 254, 254))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(lblQbteEstoqAtual)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtQnteEstoqAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lblQnteCompra)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtQnteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(lblQnteeEstqMinimo)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtQnteEstoqMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addComponent(lblLote)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lblData)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lblValidade)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(lblPrecoCusto)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                        .addComponent(lblPrecoVenda)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(Mastertable, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(lblFornecedor)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnFornecedor))
                                                        .addComponent(pnlCunsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblimagem)
                                                .addGap(91, 91, 91))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFinalizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BtnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSair)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pnlCunsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(lblFornecedor)
                                                        .addComponent(cbxFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(btnFornecedor)))
                                        .addComponent(lblimagem))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblMedicamento)
                                        .addComponent(cbxMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMedicamento))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblLote)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblData)
                                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblValidade)
                                                .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPrecoCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblPrecoCusto)
                                                .addComponent(lblPrecoVenda)
                                                .addComponent(txtPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblQbteEstoqAtual)
                                        .addComponent(lblQnteCompra)
                                        .addComponent(txtQnteEstoqAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtQnteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblQnteeEstqMinimo)
                                        .addComponent(txtQnteEstoqMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Mastertable, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnFinalizar)
                                        .addComponent(BtnCancelar)
                                        .addComponent(btnEditar)
                                        .addComponent(btnSair))
                                .addContainerGap())
                );

                bindingGroup.bind();

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
                 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(DlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(DlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(DlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(DlgCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
        //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new DlgCompras().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BtnCancelar;
        private javax.swing.JScrollPane Mastertable;
        private javax.swing.JButton btnEditar;
        private javax.swing.JButton btnFinalizar;
        private javax.swing.JButton btnFornecedor;
        private javax.swing.JButton btnMedicamento;
        private javax.swing.JButton btnSair;
        private javax.swing.JComboBox cbxFornecedor;
        private javax.swing.JComboBox cbxMedicamento;
        private javax.persistence.EntityManager entityManager;
        private javax.swing.JTable jTable1;
        private javax.swing.JLabel lblConsultaCodigo;
        private javax.swing.JLabel lblCunsultaMedicamento;
        private javax.swing.JLabel lblData;
        private javax.swing.JLabel lblFornecedor;
        private javax.swing.JLabel lblLote;
        private javax.swing.JLabel lblMedicamento;
        private javax.swing.JLabel lblPrecoCusto;
        private javax.swing.JLabel lblPrecoVenda;
        private javax.swing.JLabel lblQbteEstoqAtual;
        private javax.swing.JLabel lblQnteCompra;
        private javax.swing.JLabel lblQnteeEstqMinimo;
        private javax.swing.JLabel lblValidade;
        private javax.swing.JLabel lblimagem;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> medicamentoList;
        private javax.persistence.Query medicamentoQuery;
        private javax.swing.JPanel pnlCunsulta;
        private javax.swing.JTextField txtConsultaCodigo;
        private javax.swing.JTextField txtConsultaMedicamento;
        private javax.swing.JTextField txtData;
        private javax.swing.JTextField txtLote;
        private javax.swing.JTextField txtPrecoCusto;
        private javax.swing.JTextField txtPrecoVenda;
        private javax.swing.JTextField txtQnteCompra;
        private javax.swing.JTextField txtQnteEstoqAtual;
        private javax.swing.JTextField txtQnteEstoqMinimo;
        private javax.swing.JTextField txtValidade;
        private org.jdesktop.beansbinding.BindingGroup bindingGroup;
        // End of variables declaration//GEN-END:variables
}
