/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alf.gerfarma.view;

/**
 *
 * @author flavio
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlArea = new javax.swing.JPanel();
        pnlFerramenta = new javax.swing.JPanel();
        tbarFerramenta = new javax.swing.JToolBar();
        btnCompra = new javax.swing.JButton();
        btnBalcao = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        bmnuPrincipal = new javax.swing.JMenuBar();
        mnuOpcoes = new javax.swing.JMenu();
        itmSobre = new javax.swing.JMenuItem();
        sepOpcao1 = new javax.swing.JPopupMenu.Separator();
        itmSair = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        itmCliente = new javax.swing.JMenuItem();
        itmFornecedor = new javax.swing.JMenuItem();
        itmFuncionario = new javax.swing.JMenuItem();
        sepCadastro1 = new javax.swing.JPopupMenu.Separator();
        itmMedicamento = new javax.swing.JMenuItem();
        itmCRM = new javax.swing.JMenuItem();
        itmCartao = new javax.swing.JMenuItem();
        mnuOperacao = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        mnuRelatio = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem14 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GerFarma - Sistema de Gerenciamento de Farmácia");
        setBackground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlArea.setBackground(java.awt.Color.white);

        pnlFerramenta.setBackground(java.awt.Color.lightGray);

        tbarFerramenta.setRollover(true);

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/compra_48x48.png"))); // NOI18N
        btnCompra.setText("Compra");
        btnCompra.setFocusable(false);
        btnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tbarFerramenta.add(btnCompra);

        btnBalcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/balcao_48x48.png"))); // NOI18N
        btnBalcao.setText("Balcão");
        btnBalcao.setFocusable(false);
        btnBalcao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tbarFerramenta.add(btnBalcao);

        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/venda_48x48.png"))); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.setFocusable(false);
        btnVenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tbarFerramenta.add(btnVenda);

        javax.swing.GroupLayout pnlFerramentaLayout = new javax.swing.GroupLayout(pnlFerramenta);
        pnlFerramenta.setLayout(pnlFerramentaLayout);
        pnlFerramentaLayout.setHorizontalGroup(
            pnlFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbarFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlFerramentaLayout.setVerticalGroup(
            pnlFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/logo_266x248.png"))); // NOI18N

        javax.swing.GroupLayout pnlAreaLayout = new javax.swing.GroupLayout(pnlArea);
        pnlArea.setLayout(pnlAreaLayout);
        pnlAreaLayout.setHorizontalGroup(
            pnlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(266, 266, 266))
        );
        pnlAreaLayout.setVerticalGroup(
            pnlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaLayout.createSequentialGroup()
                .addComponent(pnlFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(lblLogo)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        mnuOpcoes.setMnemonic('o');
        mnuOpcoes.setText("Opções");

        itmSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        itmSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/sobre_32x32.png"))); // NOI18N
        itmSobre.setMnemonic('S');
        itmSobre.setText("Sobre");
        itmSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSobreActionPerformed(evt);
            }
        });
        mnuOpcoes.add(itmSobre);
        mnuOpcoes.add(sepOpcao1);

        itmSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        itmSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/sair_32x32.png"))); // NOI18N
        itmSair.setMnemonic('a');
        itmSair.setText("Sair");
        itmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSairActionPerformed(evt);
            }
        });
        mnuOpcoes.add(itmSair);

        bmnuPrincipal.add(mnuOpcoes);

        mnuCadastro.setMnemonic('c');
        mnuCadastro.setText("Cadastro");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });

        itmCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/cliente_32x32.png"))); // NOI18N
        itmCliente.setMnemonic('l');
        itmCliente.setText("Cliente");
        itmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmCliente);

        itmFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/fornecedor_32x32.png"))); // NOI18N
        itmFornecedor.setMnemonic('f');
        itmFornecedor.setText("Fornecedor");
        itmFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFornecedorActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmFornecedor);

        itmFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/funcionario_32x32.png"))); // NOI18N
        itmFuncionario.setMnemonic('u');
        itmFuncionario.setText("Funcionário");
        itmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFuncionarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmFuncionario);
        mnuCadastro.add(sepCadastro1);

        itmMedicamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/medicamento_32x32.png"))); // NOI18N
        itmMedicamento.setMnemonic('m');
        itmMedicamento.setText("Medicamento");
        itmMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMedicamentoActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmMedicamento);

        itmCRM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmCRM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/crm_32x32.png"))); // NOI18N
        itmCRM.setMnemonic('r');
        itmCRM.setText("CRM");
        mnuCadastro.add(itmCRM);

        itmCartao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/cartao_32x32.png"))); // NOI18N
        itmCartao.setMnemonic('t');
        itmCartao.setText("Cartão");
        mnuCadastro.add(itmCartao);

        bmnuPrincipal.add(mnuCadastro);

        mnuOperacao.setMnemonic('p');
        mnuOperacao.setText("Operação");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/compra_32x32.png"))); // NOI18N
        jMenuItem6.setMnemonic('o');
        jMenuItem6.setText("Compra");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnuOperacao.add(jMenuItem6);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/balcao_32x32.png"))); // NOI18N
        jMenuItem8.setMnemonic('b');
        jMenuItem8.setText("Balcão");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuOperacao.add(jMenuItem8);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/venda_32x32.png"))); // NOI18N
        jMenuItem7.setMnemonic('v');
        jMenuItem7.setText("Venda");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        mnuOperacao.add(jMenuItem7);

        bmnuPrincipal.add(mnuOperacao);

        mnuRelatio.setMnemonic('r');
        mnuRelatio.setText("Relatório");

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        jMenuItem12.setMnemonic('e');
        jMenuItem12.setText("Venda por tipo de medicamento");
        mnuRelatio.add(jMenuItem12);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        jMenuItem16.setMnemonic('n');
        jMenuItem16.setText("Venda por vendedor");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        mnuRelatio.add(jMenuItem16);
        mnuRelatio.add(jSeparator3);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        jMenuItem15.setMnemonic('d');
        jMenuItem15.setText("Medicamento com estoque baixo");
        mnuRelatio.add(jMenuItem15);

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        jMenuItem13.setMnemonic('i');
        jMenuItem13.setText("Medicamento mais vendido");
        mnuRelatio.add(jMenuItem13);
        mnuRelatio.add(jSeparator4);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        jMenuItem14.setMnemonic('a');
        jMenuItem14.setText("Faturamento Mensal");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mnuRelatio.add(jMenuItem14);

        bmnuPrincipal.add(mnuRelatio);

        setJMenuBar(bmnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        
    }//GEN-LAST:event_mnuCadastroActionPerformed

    private void itmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSairActionPerformed
        // Fecha GerFarma
        System.exit(0);
    }//GEN-LAST:event_itmSairActionPerformed

    private void itmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmClienteActionPerformed
        new PnlCliente().mostrar(this);
    }//GEN-LAST:event_itmClienteActionPerformed

    private void itmFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFornecedorActionPerformed
    }//GEN-LAST:event_itmFornecedorActionPerformed

    private void itmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFuncionarioActionPerformed
    }//GEN-LAST:event_itmFuncionarioActionPerformed

    private void itmMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMedicamentoActionPerformed
    }//GEN-LAST:event_itmMedicamentoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void itmSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSobreActionPerformed

    }//GEN-LAST:event_itmSobreActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new DlgLogin(this,true).setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bmnuPrincipal;
    private javax.swing.JButton btnBalcao;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnVenda;
    private javax.swing.JMenuItem itmCRM;
    private javax.swing.JMenuItem itmCartao;
    private javax.swing.JMenuItem itmCliente;
    private javax.swing.JMenuItem itmFornecedor;
    private javax.swing.JMenuItem itmFuncionario;
    private javax.swing.JMenuItem itmMedicamento;
    private javax.swing.JMenuItem itmSair;
    private javax.swing.JMenuItem itmSobre;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuOpcoes;
    private javax.swing.JMenu mnuOperacao;
    private javax.swing.JMenu mnuRelatio;
    private javax.swing.JPanel pnlArea;
    private javax.swing.JPanel pnlFerramenta;
    private javax.swing.JPopupMenu.Separator sepCadastro1;
    private javax.swing.JPopupMenu.Separator sepOpcao1;
    private javax.swing.JToolBar tbarFerramenta;
    // End of variables declaration//GEN-END:variables
}
