/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alf.gerfarma.view;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JMenuItem;

/**
 *
 * @author flavio
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlArea = new javax.swing.JPanel();
        pnlFerramenta = new javax.swing.JPanel();
        tbarFerramenta = new javax.swing.JToolBar();
        btnCompra = new javax.swing.JButton();
        btnBalcao = new javax.swing.JButton();
        btnVenda = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        bmnuPrincipal = new javax.swing.JMenuBar();
        mnuOpcoes = new javax.swing.JMenu();
        itmSobre = new javax.swing.JMenuItem();
        sepOpcao1 = new javax.swing.JPopupMenu.Separator();
        itmTrocarUsuario = new javax.swing.JMenuItem();
        itmEncerrar = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        itmCliente = new javax.swing.JMenuItem();
        itmMedico = new javax.swing.JMenuItem();
        itmFuncionario = new javax.swing.JMenuItem();
        itmFornecedor = new javax.swing.JMenuItem();
        sepCadastro1 = new javax.swing.JPopupMenu.Separator();
        itmMedicamento = new javax.swing.JMenuItem();
        itmCartao = new javax.swing.JMenuItem();
        mnuOperacao = new javax.swing.JMenu();
        itmCompra = new javax.swing.JMenuItem();
        itmBalcao = new javax.swing.JMenuItem();
        itmVenda = new javax.swing.JMenuItem();
        mnuRelatio = new javax.swing.JMenu();
        itmVTM = new javax.swing.JMenuItem();
        itmVV = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itmMEB = new javax.swing.JMenuItem();
        itmMMV = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itmFM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GerFarma - Sistema de Gerenciamento de Farmácia");
        setBackground(java.awt.Color.white);
        setIconImage(new ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/logo_32x29.png")).getImage());
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlArea.setBackground(java.awt.Color.white);

        pnlFerramenta.setBackground(java.awt.Color.lightGray);

        tbarFerramenta.setRollover(true);

        btnCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/compra_48x48.png"))); // NOI18N
        btnCompra.setText("Compra");
        btnCompra.setFocusable(false);
        btnCompra.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        tbarFerramenta.add(btnCompra);

        btnBalcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/balcao_48x48.png"))); // NOI18N
        btnBalcao.setText("Balcão");
        btnBalcao.setFocusable(false);
        btnBalcao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBalcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalcaoActionPerformed(evt);
            }
        });
        tbarFerramenta.add(btnBalcao);

        btnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/venda_48x48.png"))); // NOI18N
        btnVenda.setText("Venda");
        btnVenda.setFocusable(false);
        btnVenda.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendaActionPerformed(evt);
            }
        });
        tbarFerramenta.add(btnVenda);

        javax.swing.GroupLayout pnlFerramentaLayout = new javax.swing.GroupLayout(pnlFerramenta);
        pnlFerramenta.setLayout(pnlFerramentaLayout);
        pnlFerramentaLayout.setHorizontalGroup(
            pnlFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbarFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlFerramentaLayout.setVerticalGroup(
            pnlFerramentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbarFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/logo_266x248.png"))); // NOI18N

        javax.swing.GroupLayout pnlAreaLayout = new javax.swing.GroupLayout(pnlArea);
        pnlArea.setLayout(pnlAreaLayout);
        pnlAreaLayout.setHorizontalGroup(
            pnlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFerramenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAreaLayout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(266, 266, 266))
        );
        pnlAreaLayout.setVerticalGroup(
            pnlAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaLayout.createSequentialGroup()
                .addComponent(pnlFerramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(lblLogo)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        mnuOpcoes.setMnemonic('o');
        mnuOpcoes.setText("Opções");

        itmSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        itmSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/sobre_32x32.png"))); // NOI18N
        itmSobre.setMnemonic('S');
        itmSobre.setText("Sobre");
        itmSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmSobreActionPerformed(evt);
            }
        });
        mnuOpcoes.add(itmSobre);
        mnuOpcoes.add(sepOpcao1);

        itmTrocarUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK));
        itmTrocarUsuario.setText("Trocar Usuário");
        itmTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTrocarUsuarioActionPerformed(evt);
            }
        });
        mnuOpcoes.add(itmTrocarUsuario);

        itmEncerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        itmEncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/sair_32x32.png"))); // NOI18N
        itmEncerrar.setMnemonic('a');
        itmEncerrar.setText("Encerrar");
        itmEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmEncerrarActionPerformed(evt);
            }
        });
        mnuOpcoes.add(itmEncerrar);

        bmnuPrincipal.add(mnuOpcoes);

        mnuCadastro.setMnemonic('c');
        mnuCadastro.setText("Cadastro");
        mnuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCadastroActionPerformed(evt);
            }
        });

        itmCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/cliente_32x32.png"))); // NOI18N
        itmCliente.setMnemonic('l');
        itmCliente.setText("Cliente");
        itmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmClienteActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmCliente);

        itmMedico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/crm_32x32.png"))); // NOI18N
        itmMedico.setText("Médico");
        itmMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMedicoActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmMedico);

        itmFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/funcionario_32x32.png"))); // NOI18N
        itmFuncionario.setMnemonic('u');
        itmFuncionario.setText("Funcionário");
        itmFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFuncionarioActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmFuncionario);

        itmFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/fornecedor_32x32.png"))); // NOI18N
        itmFornecedor.setMnemonic('f');
        itmFornecedor.setText("Fornecedor");
        itmFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFornecedorActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmFornecedor);
        mnuCadastro.add(sepCadastro1);

        itmMedicamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmMedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/medicamento_32x32.png"))); // NOI18N
        itmMedicamento.setMnemonic('r');
        itmMedicamento.setText("Medicamento");
        itmMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmMedicamentoActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmMedicamento);

        itmCartao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmCartao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/cartao_32x32.png"))); // NOI18N
        itmCartao.setMnemonic('t');
        itmCartao.setText("Cartão");
        itmCartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCartaoActionPerformed(evt);
            }
        });
        mnuCadastro.add(itmCartao);

        bmnuPrincipal.add(mnuCadastro);

        mnuOperacao.setMnemonic('p');
        mnuOperacao.setText("Operação");

        itmCompra.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/compra_32x32.png"))); // NOI18N
        itmCompra.setMnemonic('o');
        itmCompra.setText("Compra");
        itmCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCompraActionPerformed(evt);
            }
        });
        mnuOperacao.add(itmCompra);

        itmBalcao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmBalcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/balcao_32x32.png"))); // NOI18N
        itmBalcao.setMnemonic('b');
        itmBalcao.setText("Balcão");
        itmBalcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmBalcaoActionPerformed(evt);
            }
        });
        mnuOperacao.add(itmBalcao);

        itmVenda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/venda_32x32.png"))); // NOI18N
        itmVenda.setMnemonic('v');
        itmVenda.setText("Venda");
        itmVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVendaActionPerformed(evt);
            }
        });
        mnuOperacao.add(itmVenda);

        bmnuPrincipal.add(mnuOperacao);

        mnuRelatio.setMnemonic('r');
        mnuRelatio.setText("Relatório");

        itmVTM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmVTM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        itmVTM.setMnemonic('e');
        itmVTM.setText("Venda por tipo de medicamento");
        itmVTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVTMActionPerformed(evt);
            }
        });
        mnuRelatio.add(itmVTM);

        itmVV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmVV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        itmVV.setMnemonic('n');
        itmVV.setText("Venda por vendedor");
        itmVV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmVVActionPerformed(evt);
            }
        });
        mnuRelatio.add(itmVV);
        mnuRelatio.add(jSeparator3);

        itmMEB.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmMEB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        itmMEB.setMnemonic('d');
        itmMEB.setText("Medicamento com estoque baixo");
        mnuRelatio.add(itmMEB);

        itmMMV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmMMV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        itmMMV.setMnemonic('i');
        itmMMV.setText("Medicamento mais vendido");
        mnuRelatio.add(itmMMV);
        mnuRelatio.add(jSeparator4);

        itmFM.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        itmFM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/relatorio_32x32.png"))); // NOI18N
        itmFM.setMnemonic('a');
        itmFM.setText("Faturamento Mensal");
        itmFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmFMActionPerformed(evt);
            }
        });
        mnuRelatio.add(itmFM);

        bmnuPrincipal.add(mnuRelatio);

        setJMenuBar(bmnuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCadastroActionPerformed
        
    }//GEN-LAST:event_mnuCadastroActionPerformed

    private void itmEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmEncerrarActionPerformed
        // Fecha GerFarma
        System.exit(0);
    }//GEN-LAST:event_itmEncerrarActionPerformed

    private void itmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmClienteActionPerformed
        // Mostra tela de cadastro de clientes
        new PnlCliente().mostrar(this);
    }//GEN-LAST:event_itmClienteActionPerformed

    private void itmFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFornecedorActionPerformed
        // Mostra tela de cadastro de clientes
        new PnlFornecedor().mostrar(this);
    }//GEN-LAST:event_itmFornecedorActionPerformed

    private void itmFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFuncionarioActionPerformed
        // Mostra tela de cadastro de clientes
        new PnlFuncionario().mostrar(this);
    }//GEN-LAST:event_itmFuncionarioActionPerformed

    private void itmCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCompraActionPerformed
        
    }//GEN-LAST:event_itmCompraActionPerformed

    private void itmVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVendaActionPerformed
            //mostrar tela de caixa   
            new DlgCaixa().mostrar(this);        
    }//GEN-LAST:event_itmVendaActionPerformed

    private void itmBalcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmBalcaoActionPerformed
       cmdAbrirBalcao();
    }//GEN-LAST:event_itmBalcaoActionPerformed

    private void itmSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmSobreActionPerformed
        //Exibi tela sobre o sistema
        new DlgSobre(this, true).setVisible(true);
    }//GEN-LAST:event_itmSobreActionPerformed

    private void itmFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmFMActionPerformed
        
    }//GEN-LAST:event_itmFMActionPerformed

    private void itmVVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVVActionPerformed
        
    }//GEN-LAST:event_itmVVActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Exibi janela de login ao abrir o formulario principal
        new DlgLogin(this,true).setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    private void btnBalcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalcaoActionPerformed
        cmdAbrirBalcao();
    }//GEN-LAST:event_btnBalcaoActionPerformed

    private void itmCartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCartaoActionPerformed
        // Mostra tela de cadastro de cartões
        new PnlCartao().mostrar(this);
    }//GEN-LAST:event_itmCartaoActionPerformed

    private void itmMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMedicamentoActionPerformed
        // Mostra tela de cadastro de medicamentos
        new PnlMedicamento().mostrar(this);
    }//GEN-LAST:event_itmMedicamentoActionPerformed

    private void itmMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmMedicoActionPerformed
        // Mostra tela de cadastro de medicamentos
        new PnlMedico().mostrar(this);
    }//GEN-LAST:event_itmMedicoActionPerformed

    private void itmVTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmVTMActionPerformed

    }//GEN-LAST:event_itmVTMActionPerformed

        private void btnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendaActionPerformed
                // TODO add your handling code here:
                new DlgCaixa().mostrar(this);
        }//GEN-LAST:event_btnVendaActionPerformed

        private void itmTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTrocarUsuarioActionPerformed
                //Exibi janela de login ao abrir o formulario principal
                new DlgLogin(this,true).setVisible(true);
        }//GEN-LAST:event_itmTrocarUsuarioActionPerformed
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar bmnuPrincipal;
    private javax.swing.JButton btnBalcao;
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnVenda;
    private javax.swing.JMenuItem itmBalcao;
    private javax.swing.JMenuItem itmCartao;
    private javax.swing.JMenuItem itmCliente;
    private javax.swing.JMenuItem itmCompra;
    private javax.swing.JMenuItem itmEncerrar;
    private javax.swing.JMenuItem itmFM;
    private javax.swing.JMenuItem itmFornecedor;
    private javax.swing.JMenuItem itmFuncionario;
    private javax.swing.JMenuItem itmMEB;
    private javax.swing.JMenuItem itmMMV;
    private javax.swing.JMenuItem itmMedicamento;
    private javax.swing.JMenuItem itmMedico;
    private javax.swing.JMenuItem itmSobre;
    private javax.swing.JMenuItem itmTrocarUsuario;
    private javax.swing.JMenuItem itmVTM;
    private javax.swing.JMenuItem itmVV;
    private javax.swing.JMenuItem itmVenda;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenu mnuOpcoes;
    private javax.swing.JMenu mnuOperacao;
    private javax.swing.JMenu mnuRelatio;
    private javax.swing.JPanel pnlArea;
    private javax.swing.JPanel pnlFerramenta;
    private javax.swing.JPopupMenu.Separator sepCadastro1;
    private javax.swing.JPopupMenu.Separator sepOpcao1;
    private javax.swing.JToolBar tbarFerramenta;
    // End of variables declaration//GEN-END:variables

    /* Exibi janela tela de balcao */
    private void cmdAbrirBalcao() {        
        new DlgBalcao(this, true).setVisible(true); 
    }

        public JButton getBtnBalcao() {
                return btnBalcao;
        }

        public JButton getBtnCompra() {
                return btnCompra;
        }

        public JButton getBtnVenda() {
                return btnVenda;
        }

        public JMenuItem getItmCartao() {
                return itmCartao;
        }

        public JMenuItem getItmCliente() {
                return itmCliente;
        }

        public JMenuItem getItmFornecedor() {
                return itmFornecedor;
        }

        public JMenuItem getItmFuncionario() {
                return itmFuncionario;
        }

        public JMenuItem getItmMedicamento() {
                return itmMedicamento;
        }

        public JMenuItem getItmMedico() {
                return itmMedico;
        }

        public JMenuItem getItmBalcao() {
                return itmBalcao;
        }

        public JMenuItem getItmCompra() {
                return itmCompra;
        }

        public JMenuItem getItmEncerrar() {
                return itmEncerrar;
        }

        public JMenuItem getItmFM() {
                return itmFM;
        }

        public JMenuItem getItmMEB() {
                return itmMEB;
        }

        public JMenuItem getItmMMV() {
                return itmMMV;
        }

        public JMenuItem getItmSobre() {
                return itmSobre;
        }

        public JMenuItem getItmTrocarUsuario() {
                return itmTrocarUsuario;
        }

        public JMenuItem getItmVTM() {
                return itmVTM;
        }

        public JMenuItem getItmVV() {
                return itmVV;
        }

        public JMenuItem getItmVenda() {
                return itmVenda;
        }
    
    
}
