/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alf.gerfarma.view;

import java.awt.EventQueue;
import java.beans.Beans;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.RollbackException;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author allan
 */
public class PnlMedicamento extends JPanel {
    
    public PnlMedicamento() {
        initComponents();
        if (!Beans.isDesignTime()) {
            entityManager.getTransaction().begin();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {
                bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

                entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("GERFARMAPU").createEntityManager();
                query1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Medicamento m");
                list = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : org.jdesktop.observablecollections.ObservableCollections.observableList(query1.getResultList());
                entityManager0 = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("gerfarma?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
                medicamentoQuery = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT m FROM Medicamento m");
                medicamentoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : medicamentoQuery.getResultList();
                medicamentoQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT m FROM Medicamento m");
                medicamentoList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : medicamentoQuery1.getResultList();
                medicamentoQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT m FROM Medicamento m");
                medicamentoList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : medicamentoQuery2.getResultList();
                medicamentoQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT m FROM Medicamento m");
                medicamentoList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : medicamentoQuery3.getResultList();
                medicamentoQuery4 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT m FROM Medicamento m");
                medicamentoList4 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : medicamentoQuery4.getResultList();
                medicamentoQuery5 = java.beans.Beans.isDesignTime() ? null : entityManager0.createQuery("SELECT m FROM Medicamento m");
                medicamentoList5 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : medicamentoQuery5.getResultList();
                masterScrollPane = new javax.swing.JScrollPane();
                masterTable = new javax.swing.JTable();
                nomeLabel = new javax.swing.JLabel();
                formulaLabel = new javax.swing.JLabel();
                fabricanteLabel = new javax.swing.JLabel();
                precoVendaLabel = new javax.swing.JLabel();
                precoCustoLabel = new javax.swing.JLabel();
                codigoDeBarrasLabel = new javax.swing.JLabel();
                tipoMedicamentoLabel = new javax.swing.JLabel();
                grupoMedicamentoLabel = new javax.swing.JLabel();
                nomeField = new javax.swing.JTextField();
                formulaField = new javax.swing.JTextField();
                fabricanteField = new javax.swing.JTextField();
                precoVendaField = new javax.swing.JTextField();
                precoCustoField = new javax.swing.JTextField();
                codigoDeBarrasField = new javax.swing.JTextField();
                saveButton = new javax.swing.JButton();
                refreshButton = new javax.swing.JButton();
                newButton = new javax.swing.JButton();
                deleteButton = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jComboBox1 = new javax.swing.JComboBox();
                jComboBox2 = new javax.swing.JComboBox();

                FormListener formListener = new FormListener();

                org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, list, masterTable);
                org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
                columnBinding.setColumnName("Nome");
                columnBinding.setColumnClass(String.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${formula}"));
                columnBinding.setColumnName("Formula");
                columnBinding.setColumnClass(String.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${fabricante}"));
                columnBinding.setColumnName("Fabricante");
                columnBinding.setColumnClass(String.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoVenda}"));
                columnBinding.setColumnName("Preco Venda");
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${precoCusto}"));
                columnBinding.setColumnName("Preco Custo");
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigoDeBarras}"));
                columnBinding.setColumnName("Codigo De Barras");
                columnBinding.setColumnClass(String.class);
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${tipoMedicamento}"));
                columnBinding.setColumnName("Tipo Medicamento");
                columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${grupoMedicamento}"));
                columnBinding.setColumnName("Grupo Medicamento");
                columnBinding.setColumnClass(String.class);
                bindingGroup.addBinding(jTableBinding);
                jTableBinding.bind();
                masterScrollPane.setViewportView(masterTable);

                nomeLabel.setText("Nome:");

                formulaLabel.setText("Formula:");

                fabricanteLabel.setText("Fabricante:");

                precoVendaLabel.setText("Preco Venda:");

                precoCustoLabel.setText("Preco Custo:");

                codigoDeBarrasLabel.setText("Codigo De Barras:");

                tipoMedicamentoLabel.setText("Tipo Medicamento:");

                grupoMedicamentoLabel.setText("Grupo Medicamento:");

                org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.nome}"), nomeField, org.jdesktop.beansbinding.BeanProperty.create("text"));
                binding.setSourceUnreadableValue("null");
                bindingGroup.addBinding(binding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), nomeField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
                bindingGroup.addBinding(binding);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.formula}"), formulaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
                binding.setSourceUnreadableValue("null");
                bindingGroup.addBinding(binding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), formulaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
                bindingGroup.addBinding(binding);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.fabricante}"), fabricanteField, org.jdesktop.beansbinding.BeanProperty.create("text"));
                binding.setSourceUnreadableValue("null");
                bindingGroup.addBinding(binding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), fabricanteField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
                bindingGroup.addBinding(binding);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.precoVenda}"), precoVendaField, org.jdesktop.beansbinding.BeanProperty.create("text"));
                binding.setSourceUnreadableValue("null");
                bindingGroup.addBinding(binding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), precoVendaField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
                bindingGroup.addBinding(binding);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.precoCusto}"), precoCustoField, org.jdesktop.beansbinding.BeanProperty.create("text"));
                binding.setSourceUnreadableValue("null");
                bindingGroup.addBinding(binding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), precoCustoField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
                bindingGroup.addBinding(binding);

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.codigoDeBarras}"), codigoDeBarrasField, org.jdesktop.beansbinding.BeanProperty.create("text"));
                binding.setSourceUnreadableValue("null");
                bindingGroup.addBinding(binding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), codigoDeBarrasField, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
                bindingGroup.addBinding(binding);

                saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/salvar_32x32.png"))); // NOI18N
                saveButton.setText("Salvar");
                saveButton.addActionListener(formListener);

                refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/atualizar_32x32.png"))); // NOI18N
                refreshButton.setText("Atualizar");
                refreshButton.addActionListener(formListener);

                newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/novo_32x32.png"))); // NOI18N
                newButton.setText("Novo");
                newButton.addActionListener(formListener);

                deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/apagar_32x32.png"))); // NOI18N
                deleteButton.setText("Excluir");

                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement != null}"), deleteButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
                bindingGroup.addBinding(binding);

                deleteButton.addActionListener(formListener);

                jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/consulta_16x16.png"))); // NOI18N
                jLabel1.setText("Pesquisa:");

                jTextField1.addActionListener(formListener);
                jTextField1.addKeyListener(formListener);

                org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, medicamentoList4, jComboBox1);
                bindingGroup.addBinding(jComboBoxBinding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.tipoMedicamento}"), jComboBox1, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
                bindingGroup.addBinding(binding);

                jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, medicamentoList5, jComboBox2);
                bindingGroup.addBinding(jComboBoxBinding);
                binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, masterTable, org.jdesktop.beansbinding.ELProperty.create("${selectedElement.grupoMedicamento}"), jComboBox2, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
                bindingGroup.addBinding(binding);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(newButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(deleteButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(refreshButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(saveButton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(nomeLabel)
                                                                        .addComponent(formulaLabel)
                                                                        .addComponent(fabricanteLabel)
                                                                        .addComponent(precoVendaLabel)
                                                                        .addComponent(precoCustoLabel)
                                                                        .addComponent(codigoDeBarrasLabel)
                                                                        .addComponent(tipoMedicamentoLabel)
                                                                        .addComponent(grupoMedicamentoLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(nomeField)
                                                                        .addComponent(formulaField)
                                                                        .addComponent(fabricanteField)
                                                                        .addComponent(precoVendaField)
                                                                        .addComponent(precoCustoField)
                                                                        .addComponent(codigoDeBarrasField)
                                                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                        .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jTextField1)))))
                                .addContainerGap())
                );

                layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {deleteButton, newButton, refreshButton, saveButton});

                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(masterScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(nomeLabel)
                                        .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(formulaLabel)
                                        .addComponent(formulaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fabricanteLabel)
                                        .addComponent(fabricanteField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(precoVendaLabel)
                                        .addComponent(precoVendaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(precoCustoLabel)
                                        .addComponent(precoCustoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(codigoDeBarrasLabel)
                                        .addComponent(codigoDeBarrasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tipoMedicamentoLabel)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(grupoMedicamentoLabel)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(saveButton)
                                        .addComponent(refreshButton)
                                        .addComponent(deleteButton)
                                        .addComponent(newButton))
                                .addContainerGap())
                );

                bindingGroup.bind();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.ActionListener, java.awt.event.KeyListener {
                FormListener() {}
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                        if (evt.getSource() == saveButton) {
                                PnlMedicamento.this.saveButtonActionPerformed(evt);
                        }
                        else if (evt.getSource() == refreshButton) {
                                PnlMedicamento.this.refreshButtonActionPerformed(evt);
                        }
                        else if (evt.getSource() == newButton) {
                                PnlMedicamento.this.newButtonActionPerformed(evt);
                        }
                        else if (evt.getSource() == deleteButton) {
                                PnlMedicamento.this.deleteButtonActionPerformed(evt);
                        }
                        else if (evt.getSource() == jTextField1) {
                                PnlMedicamento.this.jTextField1ActionPerformed(evt);
                        }
                }

                public void keyPressed(java.awt.event.KeyEvent evt) {
                        if (evt.getSource() == jTextField1) {
                                PnlMedicamento.this.jTextField1KeyPressed(evt);
                        }
                }

                public void keyReleased(java.awt.event.KeyEvent evt) {
                }

                public void keyTyped(java.awt.event.KeyEvent evt) {
                }
        }// </editor-fold>//GEN-END:initComponents

    

    @SuppressWarnings("unchecked")
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        entityManager.getTransaction().rollback();
        entityManager.getTransaction().begin();
        java.util.Collection data = query1.getResultList();
        for (Object entity : data) {
            entityManager.refresh(entity);
        }
        list.clear();
        list.addAll(data);
    }//GEN-LAST:event_refreshButtonActionPerformed
    
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int[] selected = masterTable.getSelectedRows();
        List<br.com.alf.gerfarma.model.entity.Medicamento> toRemove = new ArrayList<br.com.alf.gerfarma.model.entity.Medicamento>(selected.length);
        for (int idx = 0; idx < selected.length; idx++) {
            br.com.alf.gerfarma.model.entity.Medicamento m = list.get(masterTable.convertRowIndexToModel(selected[idx]));
            toRemove.add(m);
            entityManager.remove(m);
        }
        list.removeAll(toRemove);
    }//GEN-LAST:event_deleteButtonActionPerformed
    
    private void newButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newButtonActionPerformed
        br.com.alf.gerfarma.model.entity.Medicamento m = new br.com.alf.gerfarma.model.entity.Medicamento();
        entityManager.persist(m);
        list.add(m);
        int row = list.size() - 1;
        masterTable.setRowSelectionInterval(row, row);
        masterTable.scrollRectToVisible(masterTable.getCellRect(row, 0, true));
    }//GEN-LAST:event_newButtonActionPerformed
    
    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            entityManager.getTransaction().commit();
            entityManager.getTransaction().begin();
        } catch (RollbackException rex) {
            rex.printStackTrace();
            entityManager.getTransaction().begin();
            List<br.com.alf.gerfarma.model.entity.Medicamento> merged = new ArrayList<br.com.alf.gerfarma.model.entity.Medicamento>(list.size());
            for (br.com.alf.gerfarma.model.entity.Medicamento m : list) {
                merged.add(entityManager.merge(m));
            }
            list.clear();
            list.addAll(merged);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

        private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
                // Pesquisar por medico:
            String query = "select m from Medicamento m where m.nome like :nome";
             query1 =entityManager.createQuery(query);
             query1.setParameter("nome","%"+ jTextField1.getText()+"%");
            list.clear();
            list.addAll(query1.getResultList());
                
        }//GEN-LAST:event_jTextField1KeyPressed

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jTextField1ActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTextField codigoDeBarrasField;
        private javax.swing.JLabel codigoDeBarrasLabel;
        private javax.swing.JButton deleteButton;
        private javax.persistence.EntityManager entityManager;
        private javax.persistence.EntityManager entityManager0;
        private javax.swing.JTextField fabricanteField;
        private javax.swing.JLabel fabricanteLabel;
        private javax.swing.JTextField formulaField;
        private javax.swing.JLabel formulaLabel;
        private javax.swing.JLabel grupoMedicamentoLabel;
        private javax.swing.JComboBox jComboBox1;
        private javax.swing.JComboBox jComboBox2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JTextField jTextField1;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> list;
        private javax.swing.JScrollPane masterScrollPane;
        private javax.swing.JTable masterTable;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> medicamentoList;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> medicamentoList1;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> medicamentoList2;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> medicamentoList3;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> medicamentoList4;
        private java.util.List<br.com.alf.gerfarma.model.entity.Medicamento> medicamentoList5;
        private javax.persistence.Query medicamentoQuery;
        private javax.persistence.Query medicamentoQuery1;
        private javax.persistence.Query medicamentoQuery2;
        private javax.persistence.Query medicamentoQuery3;
        private javax.persistence.Query medicamentoQuery4;
        private javax.persistence.Query medicamentoQuery5;
        private javax.swing.JButton newButton;
        private javax.swing.JTextField nomeField;
        private javax.swing.JLabel nomeLabel;
        private javax.swing.JTextField precoCustoField;
        private javax.swing.JLabel precoCustoLabel;
        private javax.swing.JTextField precoVendaField;
        private javax.swing.JLabel precoVendaLabel;
        private javax.persistence.Query query1;
        private javax.swing.JButton refreshButton;
        private javax.swing.JButton saveButton;
        private javax.swing.JLabel tipoMedicamentoLabel;
        private org.jdesktop.beansbinding.BindingGroup bindingGroup;
        // End of variables declaration//GEN-END:variables

    //Motra tela de cadastro de medicamento
    public void mostrar(JFrame f) {
        JDialog tela = new JDialog(f,true);
        tela.setContentPane(new PnlMedicamento());
        tela.setTitle("GerFarma - Cadastro de Medicamentos");
        tela.setIconImage(new ImageIcon(getClass().getResource("/br/com/alf/gerfarma/view/img/logo_32x29.png")).getImage());
        tela.pack();
        tela.setVisible(true);
    }
}
